# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x61ta_service.proto\x12\x04sync\x1a\x1fgoogle/protobuf/timestamp.proto\"h\n\x07\x44\x61taRow\x12\x11\n\tsensor_id\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\x12-\n\tcreate_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"@\n\x16UploadCompleteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rrows_received\x18\x02 \x01(\x05\"4\n\x06Sensor\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04vbat\x18\x04 \x01(\x01\x12\x0e\n\x06status\x18\x05 \x01(\t\"\'\n\x14UploadSensorResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x8b\x01\n\x0f\x44\x61taSyncService\x12\x38\n\x0cUploadSensor\x12\x0c.sync.Sensor\x1a\x1a.sync.UploadSensorResponse\x12>\n\x0fUploadSingleRow\x12\r.sync.DataRow\x1a\x1c.sync.UploadCompleteResponseB\x08Z\x06syncpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006syncpb'
  _globals['_DATAROW']._serialized_start=61
  _globals['_DATAROW']._serialized_end=165
  _globals['_UPLOADCOMPLETERESPONSE']._serialized_start=167
  _globals['_UPLOADCOMPLETERESPONSE']._serialized_end=231
  _globals['_SENSOR']._serialized_start=233
  _globals['_SENSOR']._serialized_end=285
  _globals['_UPLOADSENSORRESPONSE']._serialized_start=287
  _globals['_UPLOADSENSORRESPONSE']._serialized_end=326
  _globals['_DATASYNCSERVICE']._serialized_start=329
  _globals['_DATASYNCSERVICE']._serialized_end=468
# @@protoc_insertion_point(module_scope)
